### ISSUE TITLE
强烈要求为 enableAudioVolumeIndicator 添加上音量监听的频率参数设置

### ISSUE THREAD

**Issue by little-buddy** [anyRTC/ArWebSDK#3]
## 🚀 简述你的需求或建议添加的需求

(一句话描述你的需求)

## 为什么有个需求？

老板觉得你们音量反馈太慢了体验太差，但是跟你们技术实际沟通发现，只是没有开放出这个配置

## 这样做有什么好处？

如果自己实现其实就是再写一遍这个方法，对于开发者来说不是很友好且显得多余，为什么隔壁Android有的配置，web就没有

**Comment by Dync-BoYuan** [comment]
感谢您的反馈，我们尽快安排开发来满足您的需求

**Comment by chudongvip** [comment]
我们已经在 `client.setParameters` 自定义方法中添加 `AudioVolumeInterval` 配置项，用于自定义音频反馈的上报时间，单位为毫秒，请知悉。
